"""Stamp newly added cards once, grouped by ISO Monday, and build Dart metadata.

Run after adding vocabulary: python tool/sync_vocabulary_metadata.py --dart PATH
Existing timestamps and manually reviewed labels are preserved.
Use --added-on YYYY-MM-DD to import a known earlier addition date.
"""
import argparse
import datetime as dt
import json
from pathlib import Path
import subprocess
import sys
from zoneinfo import ZoneInfo

ROOT = Path(__file__).resolve().parent.parent
LABELS = {'noun', 'verb', 'adjective', 'adverb', 'pronoun', 'article',
          'preposition', 'conjunction', 'numeral', 'interjection'}

def monday(date):
    return (date - dt.timedelta(days=date.weekday())).isoformat()

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--dart', default='dart')
    parser.add_argument('--added-on', type=dt.date.fromisoformat)
    parser.add_argument('--timezone', default='Europe/Bucharest')
    parser.add_argument('--nlp-python', default=str(ROOT/'.dart_tool/vocabulary_nlp/Scripts/python.exe'))
    args = parser.parse_args()
    if args.added_on is None:
        args.added_on = dt.datetime.now(ZoneInfo(args.timezone)).date()
    result = subprocess.run([args.dart, 'tool/export_vocabulary.dart'], cwd=ROOT,
                            check=True, capture_output=True, encoding='utf-8')
    cards = json.loads(result.stdout)
    path = ROOT / 'tool/vocabulary_metadata.json'
    ledger = json.loads(path.read_text(encoding='utf-8')) if path.exists() else {}
    for card in cards:
        key = f'{card["source"]}.{card["sourceId"]}'
        if key not in ledger:
            ledger[key] = {'addedWeek': monday(args.added_on), 'labels':card['labels']}
    for key, entry in ledger.items():
        if entry['addedWeek'] != monday(dt.date.fromisoformat(entry['addedWeek'])):
            raise ValueError(f'{key}: timestamp must be a Monday')
        if not set(entry['labels']) <= LABELS:
            raise ValueError(f'{key}: unsupported label')
    path.write_text(json.dumps(ledger, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
    ROOT.joinpath('.dart_tool').mkdir(exist_ok=True)
    current = ROOT/'.dart_tool/vocabulary-current.json'
    current.write_text(json.dumps(cards,ensure_ascii=False),encoding='utf-8')
    hints = subprocess.run([args.dart,'tool/export_vocabulary.dart','--hints'],cwd=ROOT,
                           check=True,capture_output=True,encoding='utf-8')
    hints_path=ROOT/'.dart_tool/vocabulary-hints.json'
    hints_path.write_text(hints.stdout,encoding='utf-8')
    nlp_python=args.nlp_python if Path(args.nlp_python).exists() else sys.executable
    subprocess.run([nlp_python,'tool/annotate_greek_vocabulary.py','--input',str(current),'--hints',str(hints_path)],cwd=ROOT,check=True)
    lines = ["// Generated by tool/sync_vocabulary_metadata.py; edit the JSON ledger.",
             "import '../domain/vocabulary.dart';", "import '../domain/vocabulary_category.dart';", "import 'vocabulary_words.dart';", "",
             "const vocabularyMetadata = <String, (String, List<VocabularyLabel>)>{"]
    for key, entry in sorted(ledger.items()):
        labels = ', '.join('VocabularyLabel.'+label for label in entry['labels'])
        lines.append(f"  '{key}': ('{entry['addedWeek']}', [{labels}]),")
    lines.extend(["};", "", "VocabularyDeck withVocabularyMetadata(VocabularyDeck deck) => VocabularyDeck(",
                  "  id:deck.id, title:deck.title, subtitle:deck.subtitle, cover:deck.cover, note:deck.note,",
                  "  cards: List.unmodifiable([for (final card in deck.cards) attachMetadata(deck, card)]),", ");", "",
                  "VocabularyCard attachMetadata(VocabularyDeck deck, VocabularyCard card) {",
                  "  final origin = card.reviewIdentity ?? ReviewIdentity(deckId:deck.id, cardId:card.id);",
                  "  final metadata = vocabularyMetadata['${origin.deckId}.${origin.cardId}'];",
                  "  final words = vocabularyWords['${origin.deckId}.${origin.cardId}'] ?? card.words;",
                  "  final labels = {...?metadata?.$2, ...card.labels, for(final word in words) ...word.labels};",
                  "  return card.withMetadata(addedWeek:metadata?.$1, labels:labels.toList(growable:false), words:words);", "}"])
    (ROOT/'lib/data/vocabulary_metadata.dart').write_text('\n'.join(lines)+'\n', encoding='utf-8')
    subprocess.run([args.dart, 'format', 'lib/data/vocabulary_metadata.dart'],
                   cwd=ROOT, check=True, capture_output=True)
    subprocess.run([args.dart,'format','lib/data/vocabulary_words.dart'],cwd=ROOT,check=True,capture_output=True)
    print(f'Ready: {len(ledger)} stable card timestamps')

if __name__ == '__main__':
    main()
